// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       // case TargetPlatform.iOS:
//       //   return ios;
//       // case TargetPlatform.macOS:
//       //   return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyC9oi0P2uhxjpfbVBDBei6LgNrB1HL8XKA',
//     appId: '1:1026012721818:android:a5062bc35d56ea7ed5a523',
//     messagingSenderId: '1026012721818',
//     projectId: 'DSP Project',
//     // authDomain: 'centumlms.firebaseapp.com',
//     // storageBucket: 'centumlms.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyC9oi0P2uhxjpfbVBDBei6LgNrB1HL8XKA',
//     appId: '1:1026012721818:android:a5062bc35d56ea7ed5a523',
//     messagingSenderId: '1026012721818',
//     projectId: 'DSP Project',
//    // storageBucket: 'centumlms.appspot.com',
//   );
//
//   // static const FirebaseOptions ios = FirebaseOptions(
//   //   apiKey: 'AIzaSyC9oi0P2uhxjpfbVBDBei6LgNrB1HL8XKA',
//   //   appId: '1:1026012721818:android:98fa374d32ed06b7d5a523',
//   //   messagingSenderId: '1026012721818',
//   //   projectId: 'centumlms',
//   //   storageBucket: 'centumlms.appspot.com',
//   //   androidClientId: '787999971839-470p9fpfaaclt8l6cpkcjofbeqjcnipm.apps.googleusercontent.com',
//   //   iosClientId: '787999971839-s05l9shqrhcg7g1giqlqpk5t5krf3mkg.apps.googleusercontent.com',
//   //   iosBundleId: 'tranzita.centum.aiqu',
//   // );
//
//   // static const FirebaseOptions macos = FirebaseOptions(
//   //   apiKey: 'AIzaSyC9oi0P2uhxjpfbVBDBei6LgNrB1HL8XKA',
//   //   appId: '1:1026012721818:android:98fa374d32ed06b7d5a523',
//   //   messagingSenderId: '1026012721818',
//   //   projectId: 'centumlms',
//   //   storageBucket: 'centumlms.appspot.com',
//   //   androidClientId: '787999971839-470p9fpfaaclt8l6cpkcjofbeqjcnipm.apps.googleusercontent.com',
//   //   iosBundleId: 'tranzita.centum.centumMobile.RunnerTests',
//   // );
// }
